// ============================================================
//  长河 · 数据
//  结构：trunk → dynasty | chaos → (regime | person | event | work | school | reform | treaty | office)
//  一级：政权（朝代 / 乱世）
//  二级：该政权下的人物 / 事件 / 作品 / 制度 / 学派 / 变法 / 盟约
//  三级：人物/事件下的作品、亲属、关联
//
//  ★ 宋代数据完整版。年份据《宋史》《续资治通鉴长编》《宋会要辑稿》及
//    学界通行的公元对照，帝王在位年已与维基百科君主表交叉核对。
// ============================================================

const DATA = {
  root: {
    id: 'china', name: '中国', type: 'trunk',
    children: [

      /* ============================================================
         北宋 960–1127
         ============================================================ */
      {
        id: 'northern-song', name: '北宋', type: 'dynasty', from: 960, to: 1127,
        summary: '960年赵匡胤陈桥兵变建宋，定都汴京。重文抑武、二府三司、科举取士，经济文化极盛，但冗官冗兵冗费积弊，1127年靖康之变而亡。',
        children: [
          /* ---- 人物 ---- */
          { id: 'zhao-kuangyin', name: '宋太祖', type: 'person', from: 927, to: 976,
            zi: '元朗', hao: ['赵九重'], entryPath: '军功', polity: '北宋',
            summary: '宋朝开国皇帝。陈桥兵变黄袍加身，杯酒释兵权，定"重文抑武"国策，结束五代十国之乱。',
            children: [
              { id: 'chenqiao', name: '陈桥兵变', type: 'event', from: 960, to: 960 },
              { id: 'cup-of-wine', name: '杯酒释兵权', type: 'event', from: 961, to: 961 },
              { id: 'wudai-end', name: '统一中原', type: 'event', from: 960, to: 976 },
            ]},
          { id: 'zhao-guangyi', name: '宋太宗', type: 'person', from: 939, to: 997,
            zi: '廷宜', polity: '北宋',
            summary: '太祖弟。灭北汉、收吴越，但两次北伐燕云失败，此后宋对辽转守势。扩大科举取士，奠定文官政治。',
            children: [
              { id: 'beihan-end', name: '灭北汉', type: 'event', from: 979, to: 979 },
              { id: 'gaolianghe', name: '高梁河之战', type: 'event', from: 979, to: 979 },
              { id: 'yongxi-beifa', name: '雍熙北伐', type: 'event', from: 986, to: 986,
                summary: '三路伐辽，曹彬败于岐沟关，杨业殉于陈家谷，此后宋再无力北伐。' },
              { id: 'taiping-guangji', name: '《太平广记》', type: 'work', from: 977, to: 978,
                summary: '李昉等奉敕编，五百卷，古小说总集，与《太平御览》《文苑英华》并称宋初三大书。' },
              { id: 'chongwen-yuan', name: '崇文院三馆', type: 'office', from: 978, to: 997,
                summary: '建崇文院，贮三馆秘阁之书，为国家藏书与修书之所。' },
            ]},
          { id: 'zhao-heng', name: '宋真宗', type: 'person', from: 968, to: 1022,
            zi: '德昌', polity: '北宋',
            summary: '咸平之治。景德元年澶渊之盟，宋辽约为兄弟之国，宋岁输银绢，换得百余年和平。晚年崇道，东封西祀，政事渐弛。',
            children: [
              { id: 'chanyuan', name: '澶渊之盟', type: 'event', from: 1004, to: 1005 },
              { id: 'fengshan', name: '东封西祀', type: 'event', from: 1008, to: 1011 },
              { id: 'kouzhun', name: '寇准', type: 'person', from: 961, to: 1023,
                summary: '澶渊之盟的首倡者。力劝真宗亲征，成此和议。后为丁谓所构，贬死雷州。', children: [] },
              { id: 'taiping-yulan', name: '《册府元龟》', type: 'work', from: 1005, to: 1013,
                summary: '王钦若、杨亿等奉敕编，一千卷，类书之巨制。' },
            ]},
          { id: 'zhao-zhen', name: '宋仁宗', type: 'person', from: 1010, to: 1063,
            zi: '天圣', polity: '北宋',
            summary: '在位四十一年，仁厚纳谏。庆历新政昙花一现，然名臣辈出——范仲淹、欧阳修、包拯、韩琦皆其时。',
            children: [
              { id: 'qingli', name: '庆历新政', type: 'event', from: 1043, to: 1045 },
              { id: 'qingli-heyi', name: '庆历和议', type: 'event', from: 1044, to: 1044 },
              { id: 'jiaozhi-zhi', name: '嘉祐治世', type: 'event', from: 1056, to: 1063,
                summary: '仁宗晚年，朝政清明，人才极盛，苏轼兄弟即于此期登第，史称"嘉祐之治"。' },
              { id: 'renzong-shi', name: '《宋仁宗实录》', type: 'work', from: 1064, to: 1070,
                summary: '韩琦等修，记仁宗朝四十二年事。已佚，赖《长编》存其大要。' },
            ]},
          { id: 'zhao-xu-shen', name: '宋神宗', type: 'person', from: 1048, to: 1085,
            zi: '仲鍼', polity: '北宋',
            summary: '锐意改革，用王安石行新法。熙宁变法触动既得利益，引发新旧党争，贯穿此后数十年。',
            children: [
              { id: 'xining-reform', name: '熙宁变法', type: 'event', from: 1069, to: 1085 },
              { id: 'yuanfeng-reform', name: '元丰改制', type: 'event', from: 1080, to: 1082 },
              { id: 'wulongchuan', name: '五路伐夏', type: 'event', from: 1081, to: 1082,
                summary: '元丰四年五路攻西夏，败于灵州、永乐城，宋军损失惨重。' },
              { id: 'zizhitongjian-shen', name: '敕编《资治通鉴》', type: 'event', from: 1066, to: 1084,
                summary: '神宗赐名"资治通鉴"并作序，支持司马光编成此书。' },
            ]},
          { id: 'zhao-ji', name: '宋徽宗', type: 'person', from: 1082, to: 1135, polity: '北宋',
            summary: '书画冠绝古今，瘦金体、宣和画院。然怠于政事，联金灭辽（海上之盟）引狼入室，靖康被掳，死于五国城。',
            children: [
              { id: 'haishang', name: '海上之盟', type: 'event', from: 1118, to: 1120 },
              { id: 'huashi', name: '花石纲', type: 'event', from: 1105, to: 1125 },
              { id: 'xuanhe-huapu', name: '《宣和画谱》', type: 'work', from: 1120, to: 1120 },
            ]},
          { id: 'zhao-huan', name: '宋钦宗', type: 'person', from: 1100, to: 1156, polity: '北宋',
            summary: '在位仅一年余。靖康之变中与徽宗同被金人掳北，北宋亡。',
            children: [
              { id: 'jingkang-song', name: '靖康之变', type: 'event', from: 1126, to: 1127 },
            ]},

          { id: 'wang-anshi', name: '王安石', type: 'person', from: 1021, to: 1086,
            zi: '介甫', hao: ['临川先生', '半山'], polity: '北宋',
            summary: '庆历二年进士。熙宁年间两度拜相，行青苗、募役、方田均税等新法。唐宋八大家之一，创"荆公新学"。',
            children: [
              { id: 'xining-reform-w', name: '主持熙宁变法', type: 'event', from: 1069, to: 1085 },
              { id: 'shang-renshen', name: '《上仁宗皇帝言事书》', type: 'work', from: 1058, to: 1058 },
              { id: 'dengfeilai', name: '《登飞来峰》', type: 'work', from: 1050, to: 1050 },
            ]},
          { id: 'sima-guang', name: '司马光', type: 'person', from: 1019, to: 1086,
            zi: '君实', hao: ['迂叟'], polity: '北宋', entryPath: '科举', entryYear: 1038,
            summary: '宝元元年进士。反对新法，退居洛阳十五年主编《资治通鉴》。神宗崩后入朝尽废新法，未几卒，赠太师温国公。',
            children: [
              { id: 'zizhitongjian', name: '《资治通鉴》', type: 'work', from: 1066, to: 1084 },
              { id: 'yuanyou', name: '元祐更化', type: 'event', from: 1085, to: 1093 },
              { id: 'sushui-jiyi', name: '《涑水记闻》', type: 'work', from: 1060, to: 1085,
                summary: '笔记体史料，记北宋前期政事，为治宋史者所重。' },
              { id: 'sima-xun', name: '《训俭示康》', type: 'work', from: 1080, to: 1086,
                summary: '训子司马康之文，倡俭朴，为家训名篇。' },
              { id: 'luoyang-xiushi', name: '洛阳修书', type: 'event', from: 1071, to: 1084,
                summary: '因反对新法出知永兴军，后退居洛阳十五载，专心修史，成书二百九十四卷。' },
            ]},
          { id: 'su-shi', name: '苏轼', type: 'person', from: 1037, to: 1101,
            zi: '子瞻', hao: ['东坡居士'], polity: '北宋', entryPath: '科举', entryYear: 1057,
            summary: '嘉祐二年进士。诗词文书画皆臻绝顶，唐宋八大家之一。因反对新法又不满尽废新法，一生贬谪，卒于常州。',
            children: [
              { id: 'niannujiao', name: '《念奴娇·赤壁怀古》', type: 'work', from: 1082, to: 1082 },
              { id: 'chibifu', name: '《赤壁赋》', type: 'work', from: 1082, to: 1082 },
              { id: 'wutai', name: '乌台诗案', type: 'event', from: 1079, to: 1079 },
              { id: 'shuimo', name: '《水调歌头》', type: 'work', from: 1076, to: 1076 },
            ]},
          { id: 'su-xun', name: '苏洵', type: 'person', from: 1009, to: 1066,
            zi: '明允', hao: ['老泉'], polity: '北宋',
            summary: '苏轼苏辙之父。二十七岁发愤读书，与二子同登科名，世称"三苏"。长于策论，文风雄辩。',
            children: [
              { id: 'liulun', name: '《六国论》', type: 'work', from: 1040, to: 1060 },
              { id: 'quanshu', name: '《权书》', type: 'work', from: 1045, to: 1055,
                summary: '苏洵兵论十篇，论战略形势，为宋代论兵名作。' },
              { id: 'jiayou-jixian', name: '携二子入京应试', type: 'event', from: 1056, to: 1057,
                summary: '嘉祐元年携轼、辙入京，谒欧阳修，得"一日千里"之誉，三苏名动京师。' },
            ]},
          { id: 'su-zhe', name: '苏辙', type: 'person', from: 1039, to: 1112,
            zi: '子由', hao: ['颍滨遗老'], polity: '北宋', entryPath: '科举', entryYear: 1057,
            summary: '苏轼之弟。嘉祐二年与兄同榜。官至尚书右丞，为文汪洋澹泊，亦列唐宋八大家。',
            children: [
              { id: 'huangzhoulou', name: '《黄州快哉亭记》', type: 'work', from: 1083, to: 1083 },
              { id: 'luancheng-ji', name: '《栾城集》', type: 'work', from: 1070, to: 1110,
                summary: '苏辙文集，含《上枢密韩太尉书》《六国论》等。' },
              { id: 'su-zhe-bian', name: '元祐党争贬谪', type: 'event', from: 1094, to: 1101,
                summary: '绍圣后新党执政，累贬汝州、雷州、循州，与兄同历磨难。' },
            ]},
          { id: 'ouyang-xiu', name: '欧阳修', type: 'person', from: 1007, to: 1072,
            zi: '永叔', hao: ['醉翁', '六一居士'], polity: '北宋', entryPath: '科举', entryYear: 1030,
            summary: '北宋文坛盟主。主修《新唐书》、独撰《新五代史》。知贡举时取苏轼、苏辙、曾巩，嘉祐文风由是而变。',
            children: [
              { id: 'zuiwengting', name: '《醉翁亭记》', type: 'work', from: 1046, to: 1046 },
              { id: 'xin-wudaishi', name: '《新五代史》', type: 'work', from: 1035, to: 1053 },
              { id: 'xin-tangshu', name: '《新唐书》', type: 'work', from: 1044, to: 1060 },
            ]},
          { id: 'fan-zhongyan', name: '范仲淹', type: 'person', from: 989, to: 1052,
            zi: '希文', hao: ['文正'], polity: '北宋', entryPath: '科举', entryYear: 1015,
            summary: '大中祥符八年进士。庆历新政主持者，提出十事疏。戍边御西夏，羌人呼为"龙图老子"。谥文正，为文臣最上之谥。',
            children: [
              { id: 'yueyanglou', name: '《岳阳楼记》', type: 'work', from: 1046, to: 1046 },
              { id: 'qingli-fan', name: '主持庆历新政', type: 'event', from: 1043, to: 1045 },
              { id: 'shishi-shu', name: '《答手诏条陈十事》', type: 'work', from: 1043, to: 1043,
                summary: '庆历新政纲领，提出明黜陟、抑侥幸、精贡举等十项改革。' },
              { id: 'yizhuang', name: '创设义庄', type: 'event', from: 1049, to: 1052,
                summary: '于苏州置义田千亩，赡养族人，开后世范氏义庄八百年不辍之制。' },
              { id: 'shou-yan', name: '庆州御夏', type: 'event', from: 1040, to: 1043,
                summary: '知延州、庆州，筑城屯田，号令严明，西夏不敢犯，边人谣"军中有一范，西贼闻之惊破胆"。' },
            ]},
          { id: 'li-qingzhao', name: '李清照', type: 'person', from: 1084, to: 1155,
            hao: ['易安居士'], polity: '北宋', gender: '女',
            summary: '婉约词宗。与赵明诚共辑《金石录》。靖康后南渡，词风由清丽转为沉郁，晚年孤苦。',
            children: [
              { id: 'shengshengman', name: '《声声慢》', type: 'work', from: 1150, to: 1155 },
              { id: 'wulingchun', name: '《武陵春》', type: 'work', from: 1135, to: 1135 },
              { id: 'jinshilu', name: '《金石录》', type: 'work', from: 1117, to: 1121 },
            ]},
          { id: 'shen-kuo', name: '沈括', type: 'person', from: 1031, to: 1095,
            zi: '存中', hao: ['梦溪丈人'], polity: '北宋', entryPath: '科举', entryYear: 1063,
            summary: '博学冠世。曾参与熙宁变法，出使辽廷。晚年居镇江梦溪园撰《梦溪笔谈》，记活字印刷、指南针、石油之名。',
            children: [
              { id: 'mengxi', name: '《梦溪笔谈》', type: 'work', from: 1086, to: 1093 },
              { id: 'xiuning', name: '熙宁年间使辽', type: 'event', from: 1075, to: 1075 },
              { id: 'shoujing-li', name: '《熙宁奉元历》', type: 'work', from: 1074, to: 1075,
                summary: '沈括主持编修的新历，创"十二气历"设想，比格里高利历早数百年。' },
              { id: 'yongle-cheng', name: '永乐城之败', type: 'event', from: 1082, to: 1082,
                summary: '知延州时筑永乐城，被西夏攻陷，坐贬均州，为其仕途转折。' },
              { id: 'tianyou-tu', name: '《天下州县图》', type: 'work', from: 1076, to: 1087,
                summary: '历时十二年编成的地图集，制图六体之法，为古代地图学杰作。' },
            ]},
          { id: 'bi-sheng', name: '毕昇', type: 'person', from: 970, to: 1051,
            hao: ['布衣'], polity: '北宋',
            summary: '布衣发明家。庆历年间创胶泥活字印刷术，为世界印刷史里程碑。事见《梦溪笔谈》。',
            children: [
              { id: 'huozi', name: '胶泥活字印刷术', type: 'work', from: 1041, to: 1048 },
              { id: 'mengxi-ji', name: '《梦溪笔谈》记其事', type: 'work', from: 1086, to: 1093,
                summary: '沈括《梦溪笔谈·卷十八》详载毕昇活字工艺：刻字、烧硬、排版、拆版，为唯一传世记录。' },
            ]},
          { id: 'lv-yijian', name: '吕夷简', type: 'person', from: 978, to: 1044,
            zi: '坦夫', polity: '北宋', entryPath: '科举',
            summary: '仁宗朝宰相，三度入相。与范仲淹有隙，然维持朝局；东莱吕氏由此显赫三代。',
            children: [
              { id: 'lv-gongzhu', name: '吕公著', type: 'person', from: 1018, to: 1089,
                zi: '晦叔', summary: '夷简之子。哲宗朝宰相，与司马光同主元祐更化，为洛学之友。', children: [] },
            ]},
          { id: 'fan-chunren', name: '范纯仁', type: 'person', from: 1027, to: 1101,
            zi: '尧夫', hao: ['忠宣'], polity: '北宋', entryPath: '科举',
            summary: '范仲淹次子。哲宗朝宰相，承父风节，"责己严、待人不苛"，谥忠宣。',
            children: [
              { id: 'fanshi-yizhuang', name: '续办范氏义庄', type: 'event', from: 1052, to: 1100,
                summary: '承父志续营苏州义庄，立规矩，使范氏义庄延续八百年。' },
            ]},
          { id: 'wang-pang', name: '王雱', type: 'person', from: 1044, to: 1076,
            zi: '元泽', polity: '北宋',
            summary: '王安石之子。少年英才，助父修《三经新义》，为新学中坚，惜早卒，年仅三十三。',
            children: [
              { id: 'sanjing-xinyi', name: '《三经新义》', type: 'work', from: 1073, to: 1075,
                summary: '王安石、王雱父子撰，重释《诗》《书》《周礼》，定为科举经义标准。' },
            ]},
          { id: 'wang-anli', name: '王安礼', type: 'person', from: 1034, to: 1106,
            zi: '和甫', polity: '北宋', entryPath: '科举',
            summary: '王安石之弟。官至尚书左丞，与兄政见略有出入，长于文辞。',
            children: []},
          { id: 'baozheng', name: '包拯', type: 'person', from: 999, to: 1062,
            zi: '希仁', hao: ['包孝肃', '包青天'], polity: '北宋', entryPath: '科举', entryYear: 1027,
            summary: '天圣五年进士。知开封府，执法不阿，权贵敛手。后世演绎为铁面无私的清官典范。',
            children: [
              { id: 'bao-qingtian', name: '包青天形象', type: 'work', from: 1300, to: 1900,
                summary: '元杂剧《陈州粜米》、明清小说《三侠五义》塑造的黑脸月牙形象，非史实，然影响深远。' },
              { id: 'bao-zouyi', name: '《包孝肃公奏议》', type: 'work', from: 1040, to: 1062,
                summary: '包拯奏议文集，存一百七十余篇，可见其弹劾权贵、请罢苛政之言。' },
            ]},

          /* ---- 制度 / 机构（作为条目挂在政权下）---- */
          { id: 'erfu-sansi', name: '二府三司', type: 'office', from: 960, to: 1127,
            summary: '宋代中枢：中书门下（政）、枢密院（军）为"二府"，三司（盐铁/度支/户部）掌财。相权被分割，皇帝集权。' },
          { id: 'shumiyuan', name: '枢密院', type: 'office', from: 960, to: 1279,
            summary: '掌军机、武臣铨选与边防。与中书门下并称二府。' },
          { id: 'sansi', name: '三司', type: 'office', from: 960, to: 1080,
            summary: '盐铁、度支、户部合称，总揽财计。元丰改制后归户部。' },
          { id: 'keju-song', name: '科举取士', type: 'office', from: 960, to: 1279,
            summary: '宋代科举制度化：糊名、誊录、殿试成为定制，取士额大增，士人由此崛起，门阀式微。' },
          { id: 'taijian', name: '台谏制度', type: 'office', from: 960, to: 1279,
            summary: '御史台与谏院合称台谏，掌纠弹百官。宋代台谏权重，为党争重要战场。' },
          { id: 'jingluesi', name: '经略安抚司', type: 'office', from: 960, to: 1279,
            summary: '掌一路兵民之事，多置于沿边要地（如陕西、河东），应付西夏与辽。' },

          /* ---- 学派 ---- */
          { id: 'jinggong-xinxue', name: '荆公新学', type: 'school', from: 1069, to: 1127,
            summary: '王安石所创，以《三经新义》为经义标准，为熙宁变法提供理论基础。' },
          { id: 'luoxue-xing', name: '洛学（萌芽）', type: 'school', from: 1050, to: 1127,
            summary: '程颢程颐所创，讲"天理"，为朱熹理学之源。元祐时一度遭禁（元祐党禁）。' },
          { id: 'guanxue', name: '关学', type: 'school', from: 1050, to: 1127,
            summary: '张载所创，以"气本论"与"横渠四句"闻名。' },
          { id: 'shuxue-su', name: '蜀学', type: 'school', from: 1050, to: 1127,
            summary: '苏轼父子之学，兼采佛道，与洛学对峙。' },

          /* ---- 变法 ---- */
          { id: 'xining-laws', name: '青苗法', type: 'reform', from: 1069, to: 1085,
            summary: '青黄不接时官贷钱谷于民，取二分息。本意抑兼并，行则扰民。' },
          { id: 'muyifa', name: '募役法', type: 'reform', from: 1070, to: 1085,
            summary: '改差役为雇役，民出免役钱。为宋代最受争议的新法之一。' },
          { id: 'baojiafa', name: '保甲法', type: 'reform', from: 1070, to: 1085,
            summary: '十家为保，闲时习武，渐代募兵。意在省兵费、强地方。' },
          { id: 'fangtian', name: '方田均税法', type: 'reform', from: 1072, to: 1085,
            summary: '清丈土地、按色定税，以均税负。触及隐田豪强利益，推行艰难。' },
          { id: 'shiyi', name: '市易法', type: 'reform', from: 1072, to: 1085,
            summary: '官设市易务，平价收售货物，抑商人垄断。' },

          /* ---- 盟约 ---- */
          { id: 'chanyuan-treaty', name: '澶渊之盟', type: 'treaty', from: 1005, to: 1005,
            summary: '宋辽约和：宋岁输银十万两、绢二十万匹，约为兄弟之国。此后百余年边境无事。' },
          { id: 'qingli-treaty', name: '庆历和议', type: 'treaty', from: 1044, to: 1044,
            summary: '宋夏约和，西夏称臣，宋岁赐银绢茶。' },
        ]
      },

      /* ============================================================
         辽 907–1125（与北宋并立）
         ============================================================ */
      {
        id: 'liao', name: '辽', type: 'chaos', from: 907, to: 1125,
        summary: '契丹耶律氏所建，916年耶律阿保机称帝，947年改国号辽。据燕云十六州，与北宋长期并立。1125年为金所灭。',
        children: [
          { id: 'yelu-abaoji', name: '耶律阿保机', type: 'regime', from: 872, to: 926,
            summary: '辽太祖。统一契丹诸部，916年称帝，创契丹文字。',
            children: [
              { id: 'qidan-zi', name: '创制契丹文字', type: 'work', from: 920, to: 920 },
            ]},
          { id: 'yelu-deguang', name: '耶律德光', type: 'regime', from: 902, to: 947,
            summary: '辽太宗。助石敬瑭灭后唐，得燕云十六州，947年入汴改国号"大辽"。' },
          { id: 'xiao-yanyan', name: '萧太后', type: 'regime', from: 953, to: 1009,
            summary: '辽景宗后，承天皇太后。圣宗年幼时摄政，1004年亲征伐宋，成澶渊之盟。' },
          { id: 'yelu-longxu', name: '辽圣宗', type: 'regime', from: 972, to: 1031,
            summary: '在位四十九年，辽之极盛。与宋盟好，制度汉化。' },
          { id: 'yanyun', name: '燕云十六州', type: 'event', from: 938, to: 1125,
            summary: '936年石敬瑭割予契丹，历宋三百余年未复。为北宋国防致命缺口。' },
          { id: 'liao-song-war', name: '宋辽战争', type: 'event', from: 979, to: 1004,
            summary: '太宗灭北汉后两度北伐燕云，皆败。真宗时辽军南下，遂有澶渊之盟。' },
          { id: 'liao-guozhi', name: '南北面官制', type: 'office', from: 916, to: 1125,
            summary: '辽以国制治契丹、汉制待汉人。北面官管宫帐部族，南面官仿唐制治理汉地，为"因俗而治"之典范。' },
          { id: 'liao-keju', name: '辽代科举', type: 'office', from: 988, to: 1125,
            summary: '圣宗后仿宋行科举，主要取汉人，契丹人少与。为辽吸纳汉地人才之途。' },
          { id: 'qidan-wenzi', name: '契丹文', type: 'work', from: 920, to: 1125,
            summary: '阿保机命耶律突吕不等制契丹大字，后制小字。与西夏文、女真文并称北方民族文字。' },
          { id: 'liaoshi', name: '《辽史》', type: 'work', from: 1343, to: 1344,
            summary: '元脱脱等撰，一百一十六卷。为二十四史中唯一系统记载辽朝之史，然疏略，多赖《辽史》与碑刻互证。' },
          { id: 'shangjing', name: '辽上京临潢府', type: 'regime', from: 918, to: 1120,
            summary: '契丹都城，今内蒙古巴林左旗。城分汉城与皇城，为辽"四时捺钵"之外的行政中心。' },
        ]
      },

      /* ============================================================
         西夏 1038–1227
         ============================================================ */
      {
        id: 'western-xia', name: '西夏', type: 'chaos', from: 1038, to: 1227,
        summary: '党项拓跋氏所建，1038年李元昊称帝，都兴庆府。据河西走廊，与宋辽金鼎立。1227年为蒙古所灭。',
        children: [
          { id: 'li-yuanhao', name: '李元昊', type: 'regime', from: 1003, to: 1048,
            summary: '西夏景宗。1038年称帝，创西夏文，三川口、好水川屡败宋军。',
            children: [
              { id: 'tangut-wen', name: '创制西夏文', type: 'work', from: 1036, to: 1036 },
            ]},
          { id: 'song-xia-war', name: '宋夏战争', type: 'event', from: 1038, to: 1044,
            summary: '元昊称帝后与宋交兵，三川口、好水川、定川寨宋军三败，终以庆历和议收场。' },
          { id: 'haoshuichuan', name: '好水川之战', type: 'event', from: 1041, to: 1041,
            summary: '元昊设伏大败宋军，宋将任福战死。' },
          { id: 'sanchuan-kou', name: '三川口之战', type: 'event', from: 1040, to: 1040,
            summary: '元昊攻延州，宋将刘平、石元孙兵败被俘，为宋夏首次大败。' },
          { id: 'dingchuan-zhai', name: '定川寨之战', type: 'event', from: 1042, to: 1042,
            summary: '元昊再度大败宋军，宋将葛怀敏战死，关中震动。' },
          { id: 'xia-guanzhi', name: '西夏官制', type: 'office', from: 1038, to: 1227,
            summary: '仿宋制设中书、枢密、三司，又保留党项旧俗"蕃官"，汉蕃并行。' },
          { id: 'xia-wen', name: '西夏文', type: 'work', from: 1036, to: 1227,
            summary: '元昊命野利仁荣创制，六千余字，形体仿汉字而结构不同。' },
          { id: 'fanshu', name: '《番汉合时掌中珠》', type: 'work', from: 1190, to: 1190,
            summary: '西夏文与汉文对照词典，为解读西夏文之钥匙，20世纪出土于黑水城。' },
        ]
      },

      /* ============================================================
         南宋 1127–1279
         ============================================================ */
      {
        id: 'southern-song', name: '南宋', type: 'dynasty', from: 1127, to: 1279,
        summary: '1127年赵构于应天府即位，后定都临安。与金对峙，绍兴和议划淮而治。理学在此期完成体系化，经济文化续盛。1279年崖山之后亡。',
        children: [
          { id: 'zhao-gou', name: '宋高宗', type: 'person', from: 1107, to: 1187,
            zi: '德基', polity: '南宋',
            summary: '徽宗第九子。南渡建炎，用秦桧主和，杀岳飞，签绍兴和议。在位三十六年，1162年禅位孝宗，退居德寿宫二十五年。',
            children: [
              { id: 'jianyan', name: '建炎南渡', type: 'event', from: 1127, to: 1130 },
              { id: 'shaoxing-heyi-h', name: '绍兴和议', type: 'event', from: 1141, to: 1141 },
              { id: 'dingdu-linan', name: '定都临安', type: 'event', from: 1138, to: 1138,
                summary: '绍兴八年正式以临安为行在，南宋偏安格局由此定。' },
              { id: 'miao-liu', name: '苗刘兵变', type: 'event', from: 1129, to: 1129,
                summary: '苗傅、刘正彦逼高宗退位，旋被平定，为南宋初年最险的一次内变。' },
            ]},
          { id: 'yue-fei', name: '岳飞', type: 'person', from: 1103, to: 1142,
            zi: '鹏举', hao: ['岳武穆'], polity: '南宋', entryPath: '军功',
            summary: '中兴四将之首。郾城大破金军，进军朱仙镇，为秦桧以十二金牌召回。1142年以"莫须有"冤死风波亭。',
            children: [
              { id: 'yuefei-north', name: '岳飞北伐', type: 'event', from: 1134, to: 1140 },
              { id: 'fengboting', name: '风波亭之狱', type: 'event', from: 1141, to: 1142 },
              { id: 'manjianghong', name: '《满江红》', type: 'work', from: 1136, to: 1140 },
            ]},
          { id: 'qin-hui', name: '秦桧', type: 'person', from: 1090, to: 1155,
            zi: '会之', polity: '南宋', entryPath: '科举', entryYear: 1115,
            summary: '政和五年进士。靖康被掳北去，后归南宋。两据相位十九年，主和议、构陷岳飞，为后世所唾。',
            children: [
              { id: 'qin-hui-heyi', name: '主持绍兴和议', type: 'event', from: 1141, to: 1141 },
              { id: 'moxuyou', name: '构陷岳飞', type: 'event', from: 1141, to: 1142 },
            ]},
          { id: 'han-shizhong', name: '韩世忠', type: 'person', from: 1090, to: 1151,
            zi: '良臣', hao: ['清凉居士'], polity: '南宋', entryPath: '军功',
            summary: '中兴四将之一。黄天荡之战困金兀术四十八日。岳飞冤狱时当面诘秦桧。',
            children: [
              { id: 'huangtiandang-zhan', name: '黄天荡之战', type: 'event', from: 1130, to: 1130 },
              { id: 'liang-hongyu', name: '梁红玉', type: 'person', from: 1102, to: 1135,
                summary: '韩世忠妻。黄天荡之战亲执桴鼓助战，为南宋著名女将。', children: [] },
            ]},
          { id: 'xin-qiji', name: '辛弃疾', type: 'person', from: 1140, to: 1207,
            zi: '幼安', hao: ['稼轩'], polity: '南宋',
            summary: '生于金占区，二十一岁起义南归。豪放词宗，与苏轼并称"苏辛"。一生力主北伐而不得用，存词六百余首，为宋人之冠。',
            children: [
              { id: 'yongyule', name: '《永遇乐·京口北固亭怀古》', type: 'work', from: 1205, to: 1205 },
              { id: 'qingyulan', name: '《青玉案·元夕》', type: 'work', from: 1170, to: 1174 },
              { id: 'pobuzi', name: '《破阵子·为陈同甫赋壮词以寄之》', type: 'work', from: 1188, to: 1188 },
              { id: 'meiqin-shi', name: '《美芹十论》', type: 'work', from: 1165, to: 1165,
                summary: '上孝宗书，陈抗金复国方略十篇，然未获采纳。' },
              { id: 'feihu-qi', name: '率五十骑闯金营', type: 'event', from: 1162, to: 1162,
                summary: '南归前，率五十骑突入金营，缚叛将张安国而归，一时名重。' },
            ]},
          { id: 'lu-you', name: '陆游', type: 'person', from: 1125, to: 1210,
            zi: '务观', hao: ['放翁'], polity: '南宋', entryPath: '科举',
            summary: '存诗九千余首，为古代最多产诗人。终身呼号北伐，临终仍作《示儿》。',
            children: [
              { id: 'shier', name: '《示儿》', type: 'work', from: 1210, to: 1210 },
              { id: 'chaitoufeng', name: '《钗头凤》', type: 'work', from: 1155, to: 1155 },
              { id: 'you-shanxi', name: '《游山西村》', type: 'work', from: 1167, to: 1167 },
              { id: 'shu-fen', name: '《书愤》', type: 'work', from: 1186, to: 1186 },
              { id: 'nan-zheng', name: '南郑从军', type: 'event', from: 1172, to: 1172,
                summary: '入四川宣抚使王炎幕，亲历抗金前线，为其一生最壮怀之期。' },
            ]},
          { id: 'zhu-xi', name: '朱熹', type: 'person', from: 1130, to: 1200,
            zi: '元晦', hao: ['晦庵', '紫阳'], polity: '南宋', entryPath: '科举', entryYear: 1148,
            summary: '理学的集大成者。师承二程之学，撰《四书章句集注》，此后成为科举圭臬，影响东亚六百余年。',
            children: [
              { id: 'sishu', name: '《四书章句集注》', type: 'work', from: 1182, to: 1190 },
              { id: 'zhuzi-yulei', name: '《朱子语类》', type: 'work', from: 1175, to: 1200 },
              { id: 'bailudong-jie', name: '白鹿洞书院揭示', type: 'work', from: 1179, to: 1179,
                summary: '所订学规，为中国书院教育典范，后传及朝鲜、日本。' },
              { id: 'ezhen-zhuzi', name: '鹅湖之会', type: 'event', from: 1175, to: 1175,
                summary: '与陆九渊辩论"理"与"心"，为理学与心学分歧的标志性事件。' },
              { id: 'qingyuan-dangjin', name: '庆元党禁', type: 'event', from: 1196, to: 1200,
                summary: '韩侂胄斥理学为"伪学"，朱熹遭落职，其学被禁，至死未能解。' },
            ]},
          { id: 'wen-tianxiang', name: '文天祥', type: 'person', from: 1236, to: 1283,
            zi: '宋瑞', hao: ['文山'], polity: '南宋', entryPath: '科举', entryYear: 1256,
            summary: '宝祐四年状元。元军南下，散尽家财募兵勤王，兵败被俘，囚三年不屈，1283年就义于大都。',
            children: [
              { id: 'zhengqige', name: '《正气歌》', type: 'work', from: 1281, to: 1281 },
              { id: 'guolingdingyang', name: '《过零丁洋》', type: 'work', from: 1279, to: 1279 },
              { id: 'wen-ji', name: '《文山先生全集》', type: 'work', from: 1275, to: 1283,
                summary: '含《指南录》《吟啸集》等，狱中诗文俱在。' },
              { id: 'qinwang', name: '起兵勤王', type: 'event', from: 1275, to: 1275,
                summary: '元军逼临安，文天祥散尽家财，募兵万余入卫。' },
              { id: 'yanfeng-jiuyi', name: '燕京就义', type: 'event', from: 1283, to: 1283,
                summary: '囚大都柴市三年，忽必烈亲谕降不屈，南向再拜而死，年四十七。' },
            ]},
          { id: 'zhu-song', name: '朱松', type: 'person', from: 1097, to: 1143,
            zi: '乔年', polity: '南宋', entryPath: '科举',
            summary: '朱熹之父。师事罗从彦，得二程之学，临终以程门之学托于朱熹。',
            children: []},
          { id: 'shi-hao', name: '史浩', type: 'person', from: 1106, to: 1194,
            zi: '直翁', hao: ['真隐'], polity: '南宋', entryPath: '科举',
            summary: '孝宗朝宰相，帝师。力主为岳飞平反、复其官爵，为南宋初年政局转关之臣。',
            children: [
              { id: 'yuefei-pingfan', name: '奏请为岳飞平反', type: 'event', from: 1162, to: 1163,
                summary: '孝宗即位，史浩建议追复岳飞官爵、以礼改葬，岳飞冤狱终得昭雪。' },
            ]},
          { id: 'shi-miyuan', name: '史弥远', type: 'person', from: 1164, to: 1233,
            zi: '同叔', polity: '南宋', entryPath: '科举',
            summary: '宁宗、理宗两朝专相二十六年。谋废济王、拥立理宗，权倾一时，为南宋权臣之最。',
            children: [
              { id: 'fei-jizwang', name: '矫诏废立', type: 'event', from: 1224, to: 1225,
                summary: '宁宗崩，史弥远矫诏拥立赵昀（理宗），废济王赵竑，开南宋权臣废立之端。' },
            ]},
          { id: 'shi-songzhi', name: '史嵩之', type: 'person', from: 1189, to: 1257,
            zi: '子申', polity: '南宋', entryPath: '科举',
            summary: '史弥远之侄，理宗朝宰相。主持与蒙古夹击灭金，又力主和议。',
            children: []},
          { id: 'lu-xiufu', name: '陆秀夫', type: 'person', from: 1236, to: 1279,
            zi: '君实', polity: '南宋', entryPath: '科举', entryYear: 1256,
            summary: '宝祐四年进士，与文天祥同榜。崖山之战败，负幼帝赵昺投海，南宋亡。',
            children: [
              { id: 'yashan', name: '崖山海战', type: 'event', from: 1279, to: 1279 },
              { id: 'baodi-dzv', name: '拥立端宗、帝昺', type: 'event', from: 1276, to: 1278,
                summary: '临安陷后，与张世杰等拥立端宗赵昰、帝昺赵昺，转战闽广，支撑残局。' },
            ]},

          { id: 'zhongxing-4', name: '中兴四将', type: 'office', from: 1127, to: 1160,
            summary: '岳飞、韩世忠、张俊、刘光世。南宋初年支撑半壁的四大将。' },
          { id: 'kaiti', name: '程朱理学', type: 'school', from: 1130, to: 1279,
            summary: '朱熹集大成：理气论、格物致知、存天理灭人欲。元代后成正统。' },
          { id: 'lixue-jinhua', name: '心学（萌芽）', type: 'school', from: 1150, to: 1279,
            summary: '陆九渊"心即理"，与朱熹"性即理"分庭抗礼，开明代心学先河。' },
          { id: 'shaoxing-treaty', name: '绍兴和议', type: 'treaty', from: 1141, to: 1164,
            summary: '宋金划淮水大散关为界，宋称臣纳贡，岁贡银绢各二十五万。' },
          { id: 'longxing-treaty', name: '隆兴和议', type: 'treaty', from: 1164, to: 1208,
            summary: '孝宗北伐失利后所订，改"君臣"为"叔侄"，岁贡减十万。' },
          { id: 'jiaqing-treaty', name: '嘉定和议', type: 'treaty', from: 1208, to: 1234,
            summary: '开禧北伐失败后所订，宋金改称"伯侄"，岁币增至三十万。' },
          { id: 'huizi', name: '会子', type: 'work', from: 1161, to: 1279,
            summary: '南宋纸币，初行于东南。与北宋交子同为世界最早纸币之一，后期滥发致通胀。' },
        ]
      },

      /* ============================================================
         金 1115–1234（与辽、北宋、南宋并立）
         ============================================================ */
      {
        id: 'jin', name: '金', type: 'chaos', from: 1115, to: 1234,
        summary: '女真完颜氏所建，1115年完颜阿骨打称帝。1125灭辽，1127灭北宋，与南宋对峙。1234年在宋蒙夹击下亡。',
        children: [
          { id: 'wanyan-aguda', name: '完颜阿骨打', type: 'regime', from: 1068, to: 1123,
            summary: '金太祖。统一女真诸部，1115年称帝，创女真文字。' },
          { id: 'wanyan-zongbi', name: '完颜宗弼', type: 'regime', from: 1096, to: 1148,
            summary: '即兀术。金军南下的统帅，黄天荡、郾城与宋军鏖战，后主和成绍兴和议。' },
          { id: 'wanyan-liang', name: '完颜亮', type: 'regime', from: 1122, to: 1161,
            summary: '海陵王。弑君自立，迁都燕京，1161年南侵，采石之战败，被部将所杀。' },
          { id: 'cai-shi', name: '采石之战', type: 'event', from: 1161, to: 1161,
            summary: '虞允文临危督战，以小船火器大破金水军，完颜亮南侵受挫。' },
          { id: 'jin-song-war', name: '宋金战争', type: 'event', from: 1125, to: 1164,
            summary: '靖康之变后宋金持续交战，前期宋败，后期相持，终以和议划淮分治。' },
          { id: 'jingkang-jin', name: '靖康之变', type: 'event', from: 1126, to: 1127,
            summary: '金军两度南下，破汴京，掳徽钦二帝及宗室、后妃、工匠数千人北去，北宋亡。' },
          { id: 'meng-an', name: '绍兴和议（金方）', type: 'treaty', from: 1141, to: 1161,
            summary: '金以淮水、大散关为界，宋割唐邓等州，岁贡银绢二十五万，宋金君臣名分定。' },
          { id: 'meng-an-mou', name: '海陵王迁都', type: 'event', from: 1153, to: 1153,
            summary: '完颜亮迁都燕京（中都），全面推行汉制，加速女真社会转型。' },
          { id: 'nvzhen-zi', name: '女真文', type: 'work', from: 1119, to: 1234,
            summary: '阿骨打命完颜希尹依契丹文创女真大字，后制小字。明中叶后渐废。' },
          { id: 'jin-shi', name: '《金史》', type: 'work', from: 1344, to: 1344,
            summary: '元脱脱等撰，一百三十五卷。为二十四史中体例谨严、史料较备者，清人推为良史。' },
          { id: 'zhongdu', name: '中都', type: 'regime', from: 1153, to: 1215,
            summary: '金都城，今北京。金海陵王迁都于此，为北京作为王朝都城之始。' },
        ]
      },
    ]
  },

  /* ============================================================
     家族（clan）— 宋代科举世家。据《宋史》各传世系。
     与人物为多对多：一个家族含多位人物，一个人物可属家族。
     ============================================================ */
  clans: [
    { id: 'meishan-su', name: '眉山苏氏', place: '眉州眉山', from: 1000, to: 1200,
      summary: '宋代最著名的文学世家。苏洵与二子轼、辙并称"三苏"，同列唐宋八大家，一门占其三，古今罕有。',
      members: [
        { id: 'su-xu', name: '苏序', from: 973, to: 1047, note: '祖，字仲先，乐善好施' },
        { id: 'su-xun', name: '苏洵', from: 1009, to: 1066, note: '父，字明允，号老泉' },
        { id: 'su-shi', name: '苏轼', from: 1037, to: 1101, note: '长子，字子瞻，号东坡' },
        { id: 'su-zhe', name: '苏辙', from: 1039, to: 1112, note: '次子，字子由' },
        { id: 'su-mai', name: '苏迈', from: 1059, to: 1115, note: '苏轼长子' },
        { id: 'su-guo', name: '苏过', from: 1072, to: 1123, note: '苏轼三子，号斜川居士，随父贬岭南' },
      ]},
    { id: 'luling-ouyang', name: '庐陵欧阳氏', place: '吉州庐陵', from: 1000, to: 1150,
      summary: '文坛世家。欧阳修主盟文坛三十年，子侄多发身科第。',
      members: [
        { id: 'ouyang-guan', name: '欧阳观', from: 952, to: 1010, note: '父，绵州军事推官' },
        { id: 'ouyang-xiu', name: '欧阳修', from: 1007, to: 1072, note: '字永叔，号醉翁' },
        { id: 'ouyang-fa', name: '欧阳发', from: 1046, to: 1114, note: '长子' },
        { id: 'ouyang-fei', name: '欧阳棐', from: 1047, to: 1113, note: '次子，字叔弼' },
      ]},
    { id: 'linchuan-wang', name: '临川王氏', place: '抚州临川', from: 1000, to: 1150,
      summary: '变法世家。王安石兄弟并起，王安石与其子王雱同为熙宁新法核心。',
      members: [
        { id: 'wang-yi', name: '王益', from: 993, to: 1038, note: '父，都官员外郎' },
        { id: 'wang-anshi', name: '王安石', from: 1021, to: 1086, note: '字介甫，号半山' },
        { id: 'wang-anli', name: '王安礼', from: 1034, to: 1106, note: '弟，字和甫' },
        { id: 'wang-pang', name: '王雱', from: 1044, to: 1076, note: '子，字元泽，助父修《三经新义》' },
      ]},
    { id: 'huayang-fan', name: '华阳范氏', place: '苏州吴县（原籍邠州）', from: 980, to: 1150,
      summary: '名臣世家。范仲淹四子皆有令名，纯仁位至宰相，父子两代俱以风节著称。',
      members: [
        { id: 'fan-zhongyan', name: '范仲淹', from: 989, to: 1052, note: '字希文，谥文正' },
        { id: 'fan-chunren', name: '范纯仁', from: 1027, to: 1101, note: '次子，字尧夫，官至宰相' },
        { id: 'fan-chunli', name: '范纯礼', from: 1031, to: 1106, note: '三子，字彝叟' },
        { id: 'fan-chuncui', name: '范纯粹', from: 1046, to: 1117, note: '四子，字德孺，长于边事' },
      ]},
    { id: 'lushi-donglai', name: '东莱吕氏', place: '开封（原籍东莱）', from: 970, to: 1200,
      summary: '中原望族。吕夷简、吕公著祖孙相继为相，累世显宦，为北宋最盛之世家。',
      members: [
        { id: 'lv-yijian', name: '吕夷简', from: 978, to: 1044, note: '仁宗朝宰相' },
        { id: 'lv-gongzhu', name: '吕公著', from: 1018, to: 1089, note: '夷简子，哲宗朝宰相' },
        { id: 'lv-xizhe', name: '吕希哲', from: 1039, to: 1116, note: '公著子，学者' },
      ]},
    { id: 'wuyuan-zhu', name: '婺源朱氏', place: '徽州婺源', from: 1090, to: 1300,
      summary: '理学世家。朱松以程门之学教子，朱熹集理学之大成，后世配享孔庙。',
      members: [
        { id: 'zhu-song', name: '朱松', from: 1097, to: 1143, note: '父，字乔年，师事罗从彦' },
        { id: 'zhu-xi', name: '朱熹', from: 1130, to: 1200, note: '字元晦，号晦庵' },
        { id: 'zhu-zai', name: '朱在', from: 1169, to: 1239, note: '子，官至工部侍郎' },
      ]},
    { id: 'mingzhou-shi', name: '明州史氏', place: '庆元府鄞县', from: 1100, to: 1300,
      summary: '南宋最盛宰相世家。史浩、史弥远、史嵩之三代为相，掌权近百年，亦为权臣之典型。',
      members: [
        { id: 'shi-hao', name: '史浩', from: 1106, to: 1194, note: '孝宗朝宰相，为岳飞平反' },
        { id: 'shi-miyuan', name: '史弥远', from: 1164, to: 1233, note: '宁宗、理宗朝专相二十六年' },
        { id: 'shi-songzhi', name: '史嵩之', from: 1189, to: 1257, note: '理宗朝宰相' },
      ]},
  ],

  /* ============================================================
     地点（place）— 都城 / 陪都 / 战场 / 贬谪地 / 书院
     ============================================================ */
  places: [
    { id: 'bianjing', name: '汴京', alt: ['东京', '开封府', '汴梁', '大梁'], type: '都城',
      polity: '北宋', from: 960, to: 1127,
      summary: '北宋都城，今河南开封。人逾百万，为当时世界最大城市之一。《清明上河图》所绘即此。',
      events: ['chenqiao', 'jingkang-song'] },
    { id: 'linan', name: '临安', alt: ['杭州', '武林', '钱塘'], type: '都城',
      polity: '南宋', from: 1138, to: 1276,
      summary: '南宋行在（名义陪都），今浙江杭州。1138年正式定为都城。' },
    { id: 'luoyang-song', name: '西京洛阳', alt: ['河南府', '洛'], type: '陪都',
      polity: '北宋', from: 960, to: 1127,
      summary: '北宋西京，四京之一。洛阳为理学重镇，二程居此讲学，司马光在此修《资治通鉴》。' },
    { id: 'yingtianfu', name: '南京应天府', alt: ['商丘', '宋州'], type: '陪都',
      polity: '北宋', from: 1006, to: 1127,
      summary: '北宋南京，太祖发迹之地。南宋高宗即位于此。' },
    { id: 'damingfu', name: '北京大名府', alt: ['魏州', '天雄军'], type: '陪都',
      polity: '北宋', from: 1042, to: 1127,
      summary: '北宋北京，河北军事重镇，为防辽前沿。' },
    { id: 'yanyun', name: '燕云十六州', alt: ['幽云十六州', '幽蓟'], type: '边境',
      polity: '辽', from: 938, to: 1125,
      summary: '936年石敬瑭割予契丹，含幽、蓟、瀛、莫等十六州。为北宋国防致命缺口，历三百余年未复。' },
    { id: 'chanzhou', name: '澶州', alt: ['澶渊', '开德府'], type: '战场',
      polity: '北宋', from: 1004, to: 1005,
      summary: '澶渊之盟缔结地。1004年辽军南下至澶州，真宗亲征，宋军射杀辽将萧挞凛，遂议和。' },
    { id: 'haoshuichuan-p', name: '好水川', alt: [], type: '战场',
      polity: '西夏', from: 1041, to: 1041,
      summary: '1041年宋夏激战地，元昊设伏大败宋军，宋将任福战死。' },
    { id: 'yancheng', name: '郾城', alt: [], type: '战场',
      polity: '南宋', from: 1140, to: 1140,
      summary: '1140年岳飞大破金军拐子马、铁浮图之处，岳家军进军朱仙镇。' },
    { id: 'zhuxianzhen', name: '朱仙镇', alt: [], type: '战场',
      polity: '南宋', from: 1140, to: 1140,
      summary: '岳飞北伐抵此，距汴京四十五里，金人震恐。高宗、秦桧以十二金牌召还。' },
    { id: 'huangtiandang', name: '黄天荡', alt: [], type: '战场',
      polity: '南宋', from: 1130, to: 1130,
      summary: '1130年韩世忠以八千水军困金兀术十万于此后四十八日。' },
    { id: 'caishi', name: '采石', alt: ['采石矶'], type: '战场',
      polity: '南宋', from: 1161, to: 1161,
      summary: '1161年虞允文督战大破金水军之处，完颜亮南侵受挫，后为部将所杀。' },
    { id: 'yashan', name: '崖山', alt: ['崖门'], type: '战场',
      polity: '南宋', from: 1279, to: 1279,
      summary: '1279年宋元最后决战地，陆秀夫负幼帝蹈海，南宋亡，十万军民殉国。' },
    { id: 'gaolianghe-p', name: '高梁河', alt: [], type: '战场',
      polity: '北宋', from: 979, to: 979,
      summary: '979年宋太宗伐辽败绩之处，太宗仅以身免，此后宋对辽转守。' },
    { id: 'huangzhou', name: '黄州', alt: ['齐安'], type: '贬谪地',
      polity: '北宋', from: 1080, to: 1084,
      summary: '苏轼乌台诗案后被贬此地，躬耕东坡，自号东坡居士，作《念奴娇·赤壁怀古》与前后《赤壁赋》。' },
    { id: 'huizhou', name: '惠州', alt: ['惠阳'], type: '贬谪地',
      polity: '北宋', from: 1094, to: 1097,
      summary: '苏轼再贬之地，岭南瘴疠之乡。作"日啖荔枝三百颗"句。' },
    { id: 'danzhou', name: '儋州', alt: ['昌化军'], type: '贬谪地',
      polity: '北宋', from: 1097, to: 1100,
      summary: '苏轼远谪海南之地，当时视为天涯。在此兴学授徒，开海南文教。' },
    { id: 'bailudong', name: '白鹿洞书院', alt: [], type: '书院',
      polity: '南宋', from: 1179, to: 1279,
      summary: '位于江西庐山。朱熹1179年修复并订立《白鹿洞书院揭示》，为后世书院学规典范。' },
    { id: 'yuelu', name: '岳麓书院', alt: [], type: '书院',
      polity: '南宋', from: 976, to: 1279,
      summary: '位于湖南长沙。976年创建，与白鹿洞、应天、嵩阳并称四大书院。张栻、朱熹曾会讲于此。' },
    { id: 'suiyang-shuyuan', name: '应天府书院', alt: ['睢阳书院'], type: '书院',
      polity: '北宋', from: 1009, to: 1127,
      summary: '位于应天府（今商丘）。范仲淹曾主持，为北宋最早最有影响的书院之一。' },
    { id: 'songyang', name: '嵩阳书院', alt: [], type: '书院',
      polity: '北宋', from: 1035, to: 1279,
      summary: '位于河南登封嵩山。二程曾在此讲学，为理学传播重镇。' },
  ],

  /* ============================================================
     年号（era）— 两宋 57 个正年号。数据据《宋史》本纪。
     ============================================================ */
  eras: [
    /* 北宋 */
    { id: 'jianlong', name: '建隆', polity: '北宋', emperor: '宋太祖', from: 960, to: 963 },
    { id: 'qiande', name: '乾德', polity: '北宋', emperor: '宋太祖', from: 963, to: 968 },
    { id: 'kaibao', name: '开宝', polity: '北宋', emperor: '宋太祖', from: 968, to: 976 },
    { id: 'taipingxingguo', name: '太平兴国', polity: '北宋', emperor: '宋太宗', from: 976, to: 984 },
    { id: 'yongxi', name: '雍熙', polity: '北宋', emperor: '宋太宗', from: 984, to: 987 },
    { id: 'duangong', name: '端拱', polity: '北宋', emperor: '宋太宗', from: 988, to: 989 },
    { id: 'chunhua', name: '淳化', polity: '北宋', emperor: '宋太宗', from: 990, to: 994 },
    { id: 'zhidao', name: '至道', polity: '北宋', emperor: '宋太宗', from: 995, to: 997 },
    { id: 'xianping', name: '咸平', polity: '北宋', emperor: '宋真宗', from: 998, to: 1003 },
    { id: 'jingde', name: '景德', polity: '北宋', emperor: '宋真宗', from: 1004, to: 1007 },
    { id: 'dazhongxiangfu', name: '大中祥符', polity: '北宋', emperor: '宋真宗', from: 1008, to: 1016 },
    { id: 'tianxi', name: '天禧', polity: '北宋', emperor: '宋真宗', from: 1017, to: 1021 },
    { id: 'qianxing', name: '乾兴', polity: '北宋', emperor: '宋真宗', from: 1022, to: 1022 },
    { id: 'tiansheng', name: '天圣', polity: '北宋', emperor: '宋仁宗', from: 1023, to: 1032 },
    { id: 'mingdao', name: '明道', polity: '北宋', emperor: '宋仁宗', from: 1032, to: 1033 },
    { id: 'jingyou', name: '景祐', polity: '北宋', emperor: '宋仁宗', from: 1034, to: 1037 },
    { id: 'baoyuan', name: '宝元', polity: '北宋', emperor: '宋仁宗', from: 1038, to: 1040 },
    { id: 'kangding', name: '康定', polity: '北宋', emperor: '宋仁宗', from: 1040, to: 1041 },
    { id: 'qingli', name: '庆历', polity: '北宋', emperor: '宋仁宗', from: 1041, to: 1048 },
    { id: 'huangyou', name: '皇祐', polity: '北宋', emperor: '宋仁宗', from: 1049, to: 1054 },
    { id: 'zhihe', name: '至和', polity: '北宋', emperor: '宋仁宗', from: 1054, to: 1056 },
    { id: 'jiayou', name: '嘉祐', polity: '北宋', emperor: '宋仁宗', from: 1056, to: 1063 },
    { id: 'zhiping', name: '治平', polity: '北宋', emperor: '宋英宗', from: 1064, to: 1067 },
    { id: 'xining', name: '熙宁', polity: '北宋', emperor: '宋神宗', from: 1068, to: 1077 },
    { id: 'yuanfeng', name: '元丰', polity: '北宋', emperor: '宋神宗', from: 1078, to: 1085 },
    { id: 'yuanyou', name: '元祐', polity: '北宋', emperor: '宋哲宗', from: 1086, to: 1094 },
    { id: 'shaosheng', name: '绍圣', polity: '北宋', emperor: '宋哲宗', from: 1094, to: 1098 },
    { id: 'yuanfu', name: '元符', polity: '北宋', emperor: '宋哲宗', from: 1098, to: 1100 },
    { id: 'jianzhongjingguo', name: '建中靖国', polity: '北宋', emperor: '宋徽宗', from: 1101, to: 1101 },
    { id: 'chongning', name: '崇宁', polity: '北宋', emperor: '宋徽宗', from: 1102, to: 1106 },
    { id: 'daguan', name: '大观', polity: '北宋', emperor: '宋徽宗', from: 1107, to: 1110 },
    { id: 'zhenghe', name: '政和', polity: '北宋', emperor: '宋徽宗', from: 1111, to: 1118 },
    { id: 'zhonghe', name: '重和', polity: '北宋', emperor: '宋徽宗', from: 1118, to: 1119 },
    { id: 'xuanhe', name: '宣和', polity: '北宋', emperor: '宋徽宗', from: 1119, to: 1125 },
    { id: 'jingkang', name: '靖康', polity: '北宋', emperor: '宋钦宗', from: 1126, to: 1127 },
    /* 南宋 */
    { id: 'jianyan', name: '建炎', polity: '南宋', emperor: '宋高宗', from: 1127, to: 1130 },
    { id: 'shaoxing', name: '绍兴', polity: '南宋', emperor: '宋高宗', from: 1131, to: 1162,
      note: '宋朝使用最久的年号，凡三十二年。' },
    { id: 'longxing', name: '隆兴', polity: '南宋', emperor: '宋孝宗', from: 1163, to: 1164 },
    { id: 'qiandao', name: '乾道', polity: '南宋', emperor: '宋孝宗', from: 1165, to: 1173 },
    { id: 'chunxi', name: '淳熙', polity: '南宋', emperor: '宋孝宗', from: 1174, to: 1189 },
    { id: 'shaoxi', name: '绍熙', polity: '南宋', emperor: '宋光宗', from: 1190, to: 1194 },
    { id: 'qingyuan', name: '庆元', polity: '南宋', emperor: '宋宁宗', from: 1195, to: 1200 },
    { id: 'jiatai', name: '嘉泰', polity: '南宋', emperor: '宋宁宗', from: 1201, to: 1204 },
    { id: 'kaixi', name: '开禧', polity: '南宋', emperor: '宋宁宗', from: 1205, to: 1207 },
    { id: 'jiading', name: '嘉定', polity: '南宋', emperor: '宋宁宗', from: 1208, to: 1224 },
    { id: 'baoqing', name: '宝庆', polity: '南宋', emperor: '宋理宗', from: 1225, to: 1227 },
    { id: 'shaoding', name: '绍定', polity: '南宋', emperor: '宋理宗', from: 1228, to: 1233 },
    { id: 'duanping', name: '端平', polity: '南宋', emperor: '宋理宗', from: 1234, to: 1236 },
    { id: 'jiaxi', name: '嘉熙', polity: '南宋', emperor: '宋理宗', from: 1237, to: 1240 },
    { id: 'chunyou', name: '淳祐', polity: '南宋', emperor: '宋理宗', from: 1241, to: 1252 },
    { id: 'baoyou', name: '宝祐', polity: '南宋', emperor: '宋理宗', from: 1253, to: 1258 },
    { id: 'kaiqing', name: '开庆', polity: '南宋', emperor: '宋理宗', from: 1259, to: 1259 },
    { id: 'jingding', name: '景定', polity: '南宋', emperor: '宋理宗', from: 1260, to: 1264 },
    { id: 'xianchun', name: '咸淳', polity: '南宋', emperor: '宋度宗', from: 1265, to: 1274 },
    { id: 'deyou', name: '德祐', polity: '南宋', emperor: '宋恭帝', from: 1275, to: 1276 },
    { id: 'jingyan', name: '景炎', polity: '南宋', emperor: '宋端宗', from: 1276, to: 1278 },
    { id: 'xiangxing', name: '祥兴', polity: '南宋', emperor: '宋帝昺', from: 1278, to: 1279 },
  ]
};

if (typeof window !== 'undefined') window.LONG_RIVER_DATA = DATA;
if (typeof module !== 'undefined') module.exports = DATA;
